spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql:///automatic_api
    password: root1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: ansh/

server:
  port: 9090